# Generated by Django 4.0.6 on 2022-07-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedScheduledRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidScheduleRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedBidOnScheduledRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedScheduledRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverAnnounceArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_announced', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time_sent', models.TimeField(auto_now_add=True)),
                ('date_sent', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedScheduledRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejected', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(blank=True, default='', max_length=100)),
                ('notification_tag', models.CharField(blank=True, default='', max_length=255)),
                ('notification_title', models.CharField(blank=True, max_length=255)),
                ('notification_message', models.TextField(blank=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=20)),
                ('notification_trigger', models.CharField(blank=True, choices=[('Triggered', 'Triggered'), ('Not Triggered', 'Not Triggered')], default='Triggered', max_length=255)),
                ('passengers_pickup', models.CharField(blank=True, max_length=255, null=True)),
                ('passengers_dropOff', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_ride_id', models.CharField(blank=True, max_length=255)),
                ('schedule_ride_accepted_id', models.CharField(blank=True, max_length=255)),
                ('schedule_ride_rejected_id', models.CharField(blank=True, max_length=255)),
                ('completed_schedule_ride_id', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('complain_id', models.CharField(blank=True, max_length=255)),
                ('reply_id', models.CharField(blank=True, max_length=255)),
                ('review_id', models.CharField(blank=True, max_length=255)),
                ('rating_id', models.CharField(blank=True, max_length=255)),
                ('payment_confirmed_id', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_title', models.CharField(default='', max_length=255)),
                ('schedule_type', models.CharField(choices=[('One Time', 'One Time'), ('Daily', 'Daily'), ('Days', 'Days'), ('Weekly', 'Weekly'), ('Until Cancelled', 'Until Cancelled')], default='One Time', max_length=255)),
                ('schedule_priority', models.CharField(choices=[('High', 'High'), ('Low', 'Low')], default='High', max_length=255)),
                ('schedule_description', models.TextField(default='')),
                ('pickup_location', models.CharField(blank=True, max_length=255)),
                ('drop_off_location', models.CharField(blank=True, max_length=255)),
                ('pick_up_time', models.CharField(blank=True, max_length=100)),
                ('pick_up_date', models.CharField(blank=True, max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('scheduled', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('initial_payment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_scheduled', models.DateField(auto_now_add=True)),
                ('time_scheduled', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
