# Generated by Django 4.0.6 on 2022-07-06 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_scheduling_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulednotifications',
            name='notification_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulednotifications',
            name='notification_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DeUser_receiving_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectedscheduledrides',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rejecting_scheduled_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectedscheduledrides',
            name='scheduled_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='messages',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ride_receiving_messages', to='schedule_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverannouncearrival',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_announcing_arrival', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverannouncearrival',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='completedscheduledrides',
            name='scheduled_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='completedbidonscheduledride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_completing_scheduled_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedbidonscheduledride',
            name='scheduled_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='bidscheduleride',
            name='scheduled_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scheduled_Ride_to_accept', to='schedule_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='bidscheduleride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptedscheduledrides',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_accepting_scheduled_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptedscheduledrides',
            name='scheduled_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_api.scheduleride'),
        ),
    ]
